HealthCare/Models/Pacijent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HealthCare.Models
{
    public class Pacijent
    {
        public int ID { get; set; } //PK
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Samo slova su dozvoljena.")]
        public string Prezime { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Samo slova su dozvoljena.")]
        public string Ime { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)] //Stavljen u ovaj format zbog edit dela!
        [Display(Name = "Datum Registracije")]
        public DateTime DatumRegistracije { get; set; }
        [Required]
        [Display(Name = "Naziv firme")]
        public string Firma { get; set; }

        [Display(Name = "Prezime i ime")]
        public string PunoIme { get { return Prezime + ", " + Ime; } }

        public virtual ICollection<Karton> Kartoni { get; set; } //Navigation property - sadrzace sva zakaz. za odredjen PacijentID
        public virtual ICollection<File> Files { get; set; } //1 Pacijent vise Fajlova
    }
}

HealthCare/Controllers/PacijentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HealthCare.DAL;
using HealthCare.Models;

namespace HealthCare.Controllers
{
    public class PacijentController : Controller
    {
        private HContext db = new HContext();

        // GET: Pacijent
        public ActionResult Index(string pretragaPrez)
        {
            var pacijenti = from p in db.Pacijenti select p;

            if (!String.IsNullOrEmpty(pretragaPrez))
            {
                pacijenti = pacijenti.Where
                    (p => p.Prezime.ToUpper().Contains(pretragaPrez.ToUpper()) || p.Ime.ToUpper().Contains(pretragaPrez.ToUpper()));
            }

            return View(pacijenti.ToList());
        }

        // GET: Pacijent/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Pacijent pacijent = db.Pacijenti.Find(id);
            Pacijent pacijent = db.Pacijenti.Include(p => p.Files).SingleOrDefault(p => p.ID == id);
            if (pacijent == null)
            {
                return HttpNotFound();
            }
            return View(pacijent);
        }

        // GET: Pacijent/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pacijent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Prezime,Ime,DatumRegistracije,Firma")] Pacijent pacijent, HttpPostedFileBase upload) //Sklonjen ID - automatski se unosi.. Dodata param. upload..
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0) //ContentLenght provera da nije empty file
                    {
                        var dokument = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Dokument,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            dokument.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        pacijent.Files = new List<File> { dokument }; //Dodaje u Files kolekciju u pac.
                    }
                    db.Pacijenti.Add(pacijent);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(pacijent);
        }

        // GET: Pacijent/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacijent pacijent = db.Pacijenti.Include(p => p.Files).SingleOrDefault(p => p.ID == id);
            if (pacijent == null)
            {
                return HttpNotFound();
            }
            return View(pacijent);
        }

        // POST: Pacijent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var pacijentZaUpdate = db.Pacijenti.Find(id);
            if (TryUpdateModel(pacijentZaUpdate, "",
                new string[] { "ID", "Prezime", "Ime", "DatumRegistracije", "Firma" }))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (pacijentZaUpdate.Files.Any(f => f.FileType == FileType.Dokument))
                        {
                            db.Files.Remove(pacijentZaUpdate.Files.First(f => f.FileType == FileType.Dokument));
                        }
                        var avatar = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Dokument,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            avatar.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        pacijentZaUpdate.Files = new List<File> { avatar };
                    }
                    db.Entry(pacijentZaUpdate).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DataException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(pacijentZaUpdate);
        }
        // GET: Pacijent/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacijent pacijent = db.Pacijenti.Find(id);
            if (pacijent == null)
            {
                return HttpNotFound();
            }
            return View(pacijent);
        }

        // POST: Pacijent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Pacijent pacijent = db.Pacijenti.Find(id);
            Pacijent pacijent = db.Pacijenti.Include(p => p.Files).SingleOrDefault(p => p.ID == id);            
            File file = db.Files.Include(f => f.Pacijent).SingleOrDefault(f => f.PacijentID == id);
            db.Pacijenti.Remove(pacijent);
            if (file != null)
            {
                db.Files.Remove(file);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DownloadFileSposoban()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "Files/";
            byte[] fileBytes = System.IO.File.ReadAllBytes(path + "Izvestaj Sposoban.pdf");
            string fileName = "Izvestaj Sposoban.pdf";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult DownloadFileNesposoban()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "Files/";
            byte[] fileBytes = System.IO.File.ReadAllBytes(path + "Izvestaj Nesposoban.pdf");
            string fileName = "Izvestaj Nesposoban.pdf";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HealthCare/Views/Pacijent/Create.cshtml
@model HealthCare.Models.Pacijent

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Pacijent", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pacijent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumRegistracije, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumRegistracije, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumRegistracije, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dokument", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Dokument" name="upload" /> 
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HealthCare/Views/Pacijent/Delete.cshtml
@model HealthCare.Models.Pacijent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pacijent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumRegistracije)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumRegistracije)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firma)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HealthCare/Views/Pacijent/Details.cshtml
@model HealthCare.Models.Pacijent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pacijent</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.Files.Any(f => f.FileType == HealthCare.Models.FileType.Dokument))
        {
            <dt>
                QR kod 
            </dt>
            <dd>
                <img src="~/File?id=@Model.Files.First(f => f.FileType == HealthCare.Models.FileType.Dokument).FileId" alt="dokument" />
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumRegistracije)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumRegistracije)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firma)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.Kartoni)*@Obavljeni pregledi:
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Naziv pregleda</th>
                    <th>Izveštaj</th>
                    <th>Preuzmi izveštaj</th>
                </tr>
                @foreach (var item in Model.Kartoni)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Pregled.Naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Izvestaj)
                        </td>
                        @if (item.Izvestaj == 0)
                        {
                            <td>@Html.ActionLink("Preuzmi", "DownloadFileSposoban", new { })</td>
                        }
                        else
                        {
                            <td>@Html.ActionLink("Preuzmi", "DownloadFileNesposoban", new { })</td>
                        }
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HealthCare/Views/Pacijent/Edit.cshtml
@model HealthCare.Models.Pacijent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Pacijent", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pacijent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumRegistracije, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumRegistracije, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumRegistracije, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firma, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.Files.Any(f => f.FileType == FileType.Dokument))
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Trenutni Dokument</strong></span>
                <div class="col-md-10">
                    <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Dokument).FileId" alt="avatar" />
                </div>
            </div>
        }

        <div class="form-group">
            @Html.Label("Dokument", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Dokument" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HealthCare/Views/Pacijent/Index.cshtml
@model IEnumerable<HealthCare.Models.Pacijent>

@{
    ViewBag.Title = "Index";
}

<h2>Registrovani pacijenti</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        Pretraga pacijenta: @Html.TextBox("PretragaPrez") <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumRegistracije)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Firma)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatumRegistracije)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Firma)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>