HealthCare/Models/Lekar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HealthCare.Models
{
    public class Lekar
    {
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Samo slova su dozvoljena.")]
        public string Prezime { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Samo slova su dozvoljena.")]
        public string Ime { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Zaposlen od")]
        public DateTime DatumZaposlenja { get; set; }
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email adresa")]
        public string Email { get; set; }

        [Display(Name = "Prezime i ime")]
        public string PunoIme { get { return "Dr " + Ime + " " + Prezime + ", lekar spec."; } }
        
        public virtual ICollection<LekarPregled> LekariPregledi { get; set; } //navigation prop
        public virtual ICollection<File> Files { get; set; }
    }
}

HealthCare/Controllers/LekarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HealthCare.DAL;
using HealthCare.Models;

namespace HealthCare.Controllers
{
    public class LekarController : Controller
    {
        private HContext db = new HContext();

        // GET: Lekar
        public ActionResult Index()
        {
            return View(db.Lekari.ToList());
        }

        // GET: Lekar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Lekar lekar = db.Lekari.Find(id);
            Lekar lekar = db.Lekari.Include(l => l.Files).SingleOrDefault(l => l.ID == id);//
            if (lekar == null)
            {
                return HttpNotFound();
            }
            return View(lekar);
        }

        // GET: Lekar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Lekar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Prezime,Ime,DatumZaposlenja,Email")] Lekar lekar, HttpPostedFileBase upload) //Sklonjen ID - auto..
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)//
                    {
                        var foto = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Foto,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            foto.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        lekar.Files = new List<File> { foto };
                    }
                    db.Lekari.Add(lekar);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(lekar);
        }

        // GET: Lekar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Lekar lekar = db.Lekari.Find(id);
            Lekar lekar = db.Lekari.Include(l => l.Files).SingleOrDefault(l => l.ID == id);//
            if (lekar == null)
            {
                return HttpNotFound();
            }
            return View(lekar);
        }

        // POST: Lekar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var lekarZaUpdate = db.Lekari.Find(id);
            if (TryUpdateModel(lekarZaUpdate, "",
                new string[] { "ID", "Prezime", "Ime", "DatumZaposlenja", "Email" }))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (lekarZaUpdate.Files.Any(f => f.FileType == FileType.Foto))
                        {
                            db.Files.Remove(lekarZaUpdate.Files.First(f => f.FileType == FileType.Foto));
                        }
                        var foto = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Foto,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            foto.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        lekarZaUpdate.Files = new List<File> { foto };
                    }
                    db.Entry(lekarZaUpdate).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DataException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(lekarZaUpdate);
        }
        // GET: Lekar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lekar lekar = db.Lekari.Find(id);
            if (lekar == null)
            {
                return HttpNotFound();
            }
            return View(lekar);
        }

        // POST: Lekar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Lekar lekar = db.Lekari.Find(id);
            Lekar lekar = db.Lekari.Include(p => p.Files).SingleOrDefault(p => p.ID == id);
            File file = db.Files.Include(f => f.Lekar).SingleOrDefault(f => f.LekarID == id);
            db.Lekari.Remove(lekar);
            if (file != null)
            {
                db.Files.Remove(file);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HealthCare/Views/Lekar/Create.cshtml
@model HealthCare.Models.Lekar

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Lekar", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lekar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumZaposlenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumZaposlenja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumZaposlenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Foto", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Foto" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HealthCare/Views/Lekar/Delete.cshtml
@model HealthCare.Models.Lekar

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lekar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumZaposlenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumZaposlenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HealthCare/Views/Lekar/Details.cshtml
@model HealthCare.Models.Lekar

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Lekar</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.Files.Any(f => f.FileType == FileType.Foto))
        {
            <dt>
                Fotografija
            </dt>
            <dd>
                <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Foto).FileId" alt="foto" />
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumZaposlenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumZaposlenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.LekariPregledi)*@Obavlja preglede:
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Naziv pregleda</th>
                    <th>Participacija</th>
                </tr>
                @foreach (var item in Model.LekariPregledi)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Pregled.Naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Participacija)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HealthCare/Views/Lekar/Edit.cshtml
@model HealthCare.Models.Lekar

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Lekar", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lekar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumZaposlenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumZaposlenja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumZaposlenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.Files.Any(f => f.FileType == FileType.Foto))
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Trenutna fotografija</strong></span>
                <div class="col-md-10">
                    <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Foto).FileId" alt="foto" />
                </div>
            </div>
        }

        <div class="form-group">
            @Html.Label("Foto", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Foto" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HealthCare/Views/Lekar/Index.cshtml
@model IEnumerable<HealthCare.Models.Lekar>

@{
    ViewBag.Title = "Index";
}

<h2>Lekari</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumZaposlenja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatumZaposlenja)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>